name: Deploy Laravel to Azure WebApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql, sqlite, curl, openssl
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Build frontend
        run: |
          npm ci
          npm run build

      - name: Prepare Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          mkdir -p storage bootstrap/cache database
          chmod -R 775 storage bootstrap/cache

          if grep -q "DB_CONNECTION=sqlite" .env; then
            if [ ! -f database/database.sqlite ]; then
              echo ">>> Creating new SQLite database"
              touch database/database.sqlite
            else
              echo ">>> SQLite database already exists, keeping it"
            fi
          fi

      - name: Run migrations and seed
        run: php artisan migrate:fresh --seed --force

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ictblogapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
